const {DataTypes} =  require('sequelize');
module.exports=(sequelize)=>{
    sequelize.define('form',{
        id:{
            type:DataTypes.INTEGER,
            primaryKey:true,
            autoIncrement:true,
        },
        sector:{
            type:DataTypes.STRING,
        },
        nameEvento:{
            type:DataTypes.STRING,
        },     
        nameUser:{
            type:DataTypes.STRING,
        },   
        email:{
            type:DataTypes.STRING,
        },
        fecha:{
            type:DataTypes.DATE,
        },
        horaInicio:{
            type:DataTypes.DATE,
        },
        horaFinal:{
            type:DataTypes.DATE,
        },  
        data:{
            type:DataTypes.JSON,           
        },
        estado:{
            type:DataTypes.STRING,
        },      
    });
}